GET lo
####
POST  https://jfresgister-booth-api.herokuapp.com/account/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}









####
POST https://jfresgister-booth-api.herokuapp.com/account/check
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImRhdGEiOnsiaWQiOjEsIm5hbWUiOiJBZG5pbSBOYW1lIiwicGhvbmUiOiIxMjMxMjUyMTUiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiYWRtaW4ifSwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTY1NjA4NDc4NCwiZXhwIjoxNjU2MDkxOTg0fQ.1ycSJ6fjtjkqN0uCEt3mG8VO7ppVpmdNnH4R71jQc44"
}
####
POST https://jfresgister-booth-api.herokuapp.com/account/register
Content-Type: application/json

{
    "id": 100,
    "name": "HCMUT Company",
    "phone": "0123012123",
    "email": "phatnguyencs20@hcmut.edu.vn",
    "representation": "Phat Nguyen",
    "password": "1234"
}