POST https://jfresgister-booth-api.herokuapp.com/admin/add
Content-Type: application/json

{
    "id" : 13,
    "phone": "0129312491",
    "name" : "Phat Ng",
    "email" : "qwertyu@gmail.com",
    "password": "1234"
}
####
GET https://jfresgister-booth-api.herokuapp.com/admin/all
####
GET https://jfresgister-booth-api.herokuapp.com/admin/byId/4
####
PUT https://jfresgister-booth-api.herokuapp.com/admin/update
Content-Type: application/json

{
    "id" : 13,
    "phone": "0129312491",
    "name" : "Phat Ngu",
    "email" : "qwertyu@gmail.com",
    "password": "1234"
}