GET https://jfresgister-booth-api.herokuapp.com/approve/all

####
GET https://jfresgister-booth-api.herokuapp.com/approve/byId/2
####

PUT https://jfresgister-booth-api.herokuapp.com/approve/update
Content-Type: application/json

{
    "id" : 61,
    "time_approve" : "2022-04-21 04:28:21",
    "approve": 1,
    "admin_id": 7
}