GET http://localhost:3001/approve/all
####

PUT http://localhost:3001/approve/update
Content-Type: application/json

{
    "id" : 12,
    "time_register": "2021-04-21 00:00:00",
    "time_approve" : "2022-04-21 04:28:21",
    "approve": 1,
    "booth_id": 12,
    "business_id": 13,
    "admin_id": 12
}