GET http://localhost:3001/approve/all

####
GET http://localhost:3001/approve/byId/75

####
GET http://localhost:3001/register/byId/75

####

PUT http://localhost:3001/approve/update
Content-Type: application/json

{
    "id": 63,
    "time_approve": "01:08:36, 27/6/20212",
    "approve": 1,
    "admin_id": 2
}