GET https://jfresgister-booth-api.herokuapp.com/business/all
####
GET https://jfresgister-booth-api.herokuapp.com/business/byId/69
####
POST https://jfresgister-booth-api.herokuapp.com/business/add
Content-Type: application/json

{
    "id": 69,
    "name": "HCMUT",
    "phone": "0123012123",
    "email": "hello@hcmut.edu.vn",
    "representation": "Phat Nguyen"
}
####
PUT https://jfresgister-booth-api.herokuapp.com/business/update/ 
Content-Type: application/json

{
    "id": 69,
    "name": "HCMUT",
    "phone": "0123012123",
    "email": "hello@hcmut.edu.vn",
    "representation": "Sang Nguyen",
    "password": "123456"
}
####
GET https://jfresgister-booth-api.herokuapp.com/business/maxid