GET https://jfresgister-booth-api.herokuapp.com/

####
GET https://jfresgister-booth-api.herokuapp.com/token
####
GET https://jfresgister-booth-api.herokuapp.com/check_token

// cái này t k biết lấy token ở đâu, t lấy ở link trên ép vô cũng k được nên để m xử