GET https://jfresgister-booth-api.herokuapp.com/register/byIdbooth/2
#### 
GET https://jfresgister-booth-api.herokuapp.com/register/byId/2
####
GET https://jfresgister-booth-api.herokuapp.com/register/byIdbusiness/5
####
GET https://jfresgister-booth-api.herokuapp.com/register/byIdbooth/3
####
POST https://jfresgister-booth-api.herokuapp.com/register/add
Content-Type: application/json

{
    "id": 352,
    "time_register": "2021-04-21 00:00:00",
    "business_id": 13,
    "booth_id": 12
}
####
GET https://jfresgister-booth-api.herokuapp.com/register/maxid