GET https://jfresgister-booth-api.herokuapp.com/business/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjpbeyJpZGJ1c2luZXNzIjoxMDAwLCJuYW1lIjoia2hhbmciLCJlbWFpbCI6ImtoYW5nLm5ndXllbjQxNjUiLCJwaG9uZSI6IjA5NDU0NDczNTYiLCJwYXNzd29yZCI6IktoYW5nMjAyNjIwIiwicmVwcmVzZW50YXRpb25fbmFtZSI6ImtoYW5nIn1dLCJpYXQiOjE2NTQ2NTYyNTIsImV4cCI6MTY1NDY1OTg1Mn0.oETvivqyIF-bb_wZHdpfFMjK6ePs2Dmqt1Ff_1goGoQ
####
GET https://jfresgister-booth-api.herokuapp.com/booth/all
####
GET https://jfresgister-booth-api.herokuapp.com/register/all

####
GET https://jfresgister-booth-api.herokuapp.com
####
POST https://jfresgister-booth-api.herokuapp.com/account/login
Content-Type: application/json

{
    "email": "nguyenphucbinhkhang@gmail.com",
    "password": "Khang202620"
}
####
POST https://jfresgister-booth-api.herokuapp.com/account/login
Content-Type: application/json

{
    "email": "khang.nguyen4165",
    "password": "Khang202620"
}
####
GET https://jfresgister-booth-api.herokuapp.com/haha 

#### 
POST https://jfresgister-booth-api.herokuapp.com/account/check
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImRhdGEiOnsiaWQiOjUxLCJuYW1lIjoiQ8O0bmcgVHkgS2hhbmcgVE5NVFYiLCJwaG9uZSI6IjA5NDU0NDczNTYiLCJlbWFpbCI6ImtoYW5nLm5ndXllbjQxNjVAaGNtdXQuZWR1LnZuIiwicGFzc3dvcmQiOiJLaGFuZzIwMjYyMCIsInJlcHJlc2VudGF0aW9uIjoiTVIuIEtoYW5nIn0sImlzQWRtaW4iOmZhbHNlfSwiaWF0IjoxNjU1MDkxOTgzLCJleHAiOjE2NTUwOTkxODN9.R9N3H-KY32rqqg9nCMrv4tounBvQizDS-84BXIBApfE"
}
####
GET https://jfresgister-booth-api.herokuapp.com/register/byIdbooth/2
#### 
GET https://jfresgister-booth-api.herokuapp.com/register/byId/2
####
GET https://jfresgister-booth-api.herokuapp.com/register/byIdbusiness/5

####
GET https://jfresgister-booth-api.herokuapp.com/booth/byId/5

####
GET https://jfresgister-booth-api.herokuapp.com/business/all
####
GET https://jfresgister-booth-api.herokuapp.com/business/byId/4
####
GET https://jfresgister-booth-api.herokuapp.com/booth/remove_owner/2
####
DELETE https://jfresgister-booth-api.herokuapp.com/register/delete/41